apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: tempo-monolithic
  namespace: tempo
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  management: Managed
  timeout: 1m0s
  storage:
    traces:
      backend: pv
      size: 10Gi
      storageClassName: crc-csi-hostpath-provisioner
  ingestion:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
        tls:
          enabled: false
  multitenancy:
    enabled: true
    mode: openshift
    authentication:
      - tenantName: dev
        tenantId: "11111111-1111-1111-1111-111111111111"
  jaegerui:
    enabled: false
    route:
      enabled: false
      termination: edge
  observability:
    metrics:
      serviceMonitors:
        enabled: true
      prometheusRules:
        enabled: true