apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: tempo-monolithic
  namespace: tempo
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  management: Managed
  timeout: 1m0s
  storage:
    traces:
      backend: pv
      size: 100Gi
  ingestion:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
        tls:
          enabled: false
  multitenancy:
    enabled: true
    mode: openshift
    authentication:
      - tenantName: dev
        tenantId: "11111111-1111-1111-1111-111111111111"
  jaegerui:
    enabled: false
    route:
      enabled: false
      termination: edge
  observability:
    metrics:
      serviceMonitors:
        enabled: true
      prometheusRules:
        enabled: true
  extraConfig:
    tempo:
      metrics_generator:
        storage:
          path: /var/tempo/generator/wal
        traces_storage:
          path: /var/tempo/generator/traces
        processor:
          local_blocks:
            filter_server_spans: false
            flush_to_storage: true
      overrides:
        defaults:
          metrics_generator:
            processors:
              - local-blocks
      query_frontend:
        metrics:
          max_duration: 24h
          query_backend_after: 30m
          max_exemplars: 100
          concurrent_jobs: 8
          target_bytes_per_job: 134217728
          interval: 5m
      querier:
        metrics:
          concurrent_blocks: 2
