apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: tempo-operator
  namespace: openshift-tempo-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - openshift-tempo-operator